### PR TITLE
make windows build work

### LINKED ISSUE #304: Make build windows friendly
Right now webtau cannot be built on windows due to various tests failing.

### PR DESCRIPTION
**Pull request by MykolaGolubyev**
closes #304

### CODE REVIEW

**Comment by tsiq-karold** [comment]
Can Travis (or other SaaS CI tool) run Windows builds so that those of us without a Windows machine don't accidentally introduce more OS dependent code?

**Comment by MykolaGolubyev** [comment]
@tsiq-karold I tried to add windows to travis. Unfortunately it complained that Java is not supported.

**Comment by tsiq-karold** [comment]
Wow, indeed it's not: https://docs.travis-ci.com/user/reference/windows/#supported-languages

I guess you'll have to let me know if I break it on Windows 😁

**Comment by MykolaGolubyev** [comment]
good to merge?

**Comment by tsiq-karold** [comment]
Go for it.

**Pull request merged**
